[build]
  command = "pip install -r requirements.txt"
  publish = "app/static" 
  functions = "netlify/functions"

[build.environment]
  FLASK_ENV = "production" 
  FLASK_CONFIG_TYPE = "production" 
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 