[build]
  command = "pip install -r requirements.txt"
  publish = "app/static" 
  functions = "netlify/functions"

[build.environment]
  FLASK_ENV = "production" 
  FLASK_CONFIG_TYPE = "production" 
  PYTHON_VERSION = "3.11"

# Serve static files from app/static
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Route all other requests to the Flask app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200 