[build]
builder = "nixpacks"

[deploy]
startCommand = "flask db upgrade && gunicorn run:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 